### ISSUE TITLE
Generate missing gh-pages

### ISSUE THREAD

**Issue by ctubbsii** [mojohaus/tidy-maven-plugin#1]
I created one from 1.0-beta-1 (but I had to modify the parent POM to version 34 to get it to build the site). You can see my gh-pages here:

https://github.com/ctubbsii/tidy-maven-plugin

And the site is here:

http://ctubbsii.github.io/tidy-maven-plugin

**Comment by khmarbaise** [comment]
site is no available under www.mojohaus.org/tidy-maven-plugin/

**Comment by dantran** [comment]
Hi Karl, when can I find instructions how to push maven site to some of the plugins i am working on?  Thanks

**Comment by khmarbaise** [comment]
Hi Dan i have written up a conclusions how to do that on my blog:

http://blog.soebes.de/blog/2015/06/12/making-github-page-for-mojohaus/

Kind regards.

**Comment by davidkarlsen** [comment]
Would there be any improvement to use
https://github.com/github/maven-plugins for the site publication to ghpages?

2015-06-14 16:55 GMT+02:00 Karl Heinz Marbaise <notifications@github.com>:

> Hi Dan i have written up a conclusions how to do that on my blog:
>
> http://blog.soebes.de/blog/2015/06/12/making-github-page-for-mojohaus/
>
> Kind regards.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mojohaus/tidy-maven-plugin/issues/1#issuecomment-111837655>
> .
>



-- 
--
David J. M. Karlsen - http://www.linkedin.com/in/davidkarlsen

**Comment by ctubbsii** [comment]
That's what I use.

**Comment by tchemit** [comment]
@khmarbaise thanks for the tuto, I will use it soon on some mojos project ;)
