### ISSUE TITLE
Ordering mismatch when compared to POM Code Convention

### ISSUE THREAD

**Issue by frett** [mojohaus/tidy-maven-plugin#11]
In the recommended POM Code Convention[1] `dependencyManagement` and `dependencies` come before `repositories` and `pluginRepositories`.

But currently in `EnsureOrderAndIndent.java`, `new NodeGroup( "repositories", "pluginRepositories" )` comes before `new NodeGroup( "dependencyManagement", "dependencies" )` which is backwards from the recommendation.

[1] https://maven.apache.org/developers/conventions/code.html#POM_Code_Convention

**Comment by andham** [comment]
Fixed in 754051f
