### ISSUE TITLE
The MojoHaus plugin list still states this is a “pre-release plugin”

### ISSUE THREAD

**Issue by sewe** [mojohaus/tidy-maven-plugin#17]
According to http://www.mojohaus.org/plugins.html, the latest release of the `tidy-maven-plugin` is 1.0-beta-1. This is wrong. The `tidy-maven-plugin` 1.0.0 should instead be listed as a “production plugin.”

**Comment by andham** [comment]
Fixed as part of https://github.com/mojohaus/mojohaus.github.io/commit/835f0a9a9c05ed9f24c043299042987046df3c7c
