### ISSUE TITLE
Release 1.0

### ISSUE THREAD

**Issue by mosabua** [mojohaus/tidy-maven-plugin#2]
It would be good to have the plugin available in a full release version and have all the info on the website like SCM and so on correct.. 

Also to fix https://issues.apache.org/jira/browse/MNGSITE-251 with a non-beta plugin....

**Comment by sewe** [comment]
+1

In particular, the currently released version still has a bug in it (which has since been fixed back at Codehaus) that mangles our POMs like [this](https://git.eclipse.org/r/#/c/70657/1/features/org.eclipse.recommenders.3rd.feature/pom.xml).

**Comment by khmarbaise** [comment]
VOTE for Release started..https://groups.google.com/forum/#!topic/mojohaus-dev/hQhShOpML7U

**Comment by khmarbaise** [comment]
Unfortunately i had to restart based on a wrong link on the front page...

**Comment by stefanbirkner** [comment]
The 1.0.0 release is now available from Maven Central. Thanks @khmarbaise.
