### ISSUE TITLE
Make plugin @threadSafe

### ISSUE THREAD

**Issue by sewe** [mojohaus/tidy-maven-plugin#27]
Please mark the `tidy-maven-plugin` as `@threadSafe` (likely safe, unless some underlying XML parser factory or similar isn’t).

**Comment by nbarithel** [comment]
FWIW the following warning is generated when using multiple threads :
[WARNING] *****************************************************************
[WARNING] * Your build is requesting parallel execution, but project      *
[WARNING] * contains the following plugin(s) that have goals not marked   *
[WARNING] * as @threadSafe to support parallel building.                  *
[WARNING] * While this /may/ work fine, please look for plugin updates    *
[WARNING] * and/or request plugins be made thread-safe.                   *
[WARNING] * If reporting an issue, report it against the plugin in        *
[WARNING] * question, not against maven-core                              *
[WARNING] *****************************************************************
[WARNING] The following plugins are not marked @threadSafe in XXX:
[WARNING] org.codehaus.mojo:tidy-maven-plugin:1.1.0
[WARNING] Enable debug to see more precisely which goals are not marked @threadSafe.
[WARNING] *****************************************************************
